import assert from 'assert'
import fs from 'fs'
import path from 'path'

const sourceRoot = path.resolve(__dirname)
const agentsSource = fs.readFileSync(path.join(sourceRoot, 'pages/Agents.tsx'), 'utf8')
const appSource = fs.readFileSync(path.join(sourceRoot, 'App.tsx'), 'utf8')
const pluginPageSource = fs.readFileSync(path.join(sourceRoot, 'pages/PluginWorkspacePage.tsx'), 'utf8')
const repoRoot = path.resolve(sourceRoot, '../../../..')
const manifests = [
  'PLUGINS/test/plugin-lab-guardrails/clawmax-plugin.json',
  'PLUGINS/test/plugin-lab-evals/clawmax-plugin.json',
  'PLUGINS/test/plugin-lab-review-notes/clawmax-plugin.json',
  'PLUGINS/public/clawmax-optimize/clawmax-plugin.json',
].map((relativePath) => JSON.parse(fs.readFileSync(path.join(repoRoot, relativePath), 'utf8')))

assert(
  agentsSource.includes('costTrackingEnabled = true, guardrails = []'),
  'Agent grid cards must receive a safe guardrail relationship default',
)
assert(
  (agentsSource.match(/guardrails=\{pluginRelationships\.agents\[agent\.id\] \|\| \[\]\}/g) || []).length >= 5,
  'Every agent card rendering path must receive plugin relationships',
)
assert(appSource.includes('h-[100dvh] max-h-[100dvh]'), 'The mobile sidebar must fit the dynamic viewport')
assert(appSource.includes('h-[100dvh] w-full min-w-0 overflow-hidden'), 'The app shell must not widen past the phone viewport')
assert(appSource.includes('function ChecklistIcon'), 'Release Review must have a checklist navigation icon')
assert(appSource.includes("plugin.objectKind === 'optimization-plan'"), 'Optimize must have a distinct activity navigation icon')
assert(pluginPageSource.includes("viewMode === 'grid' ? ("), 'Plugin content must render a compact grid view')
assert(pluginPageSource.includes("viewMode === 'detail' ? ("), 'Plugin content must render a detail view')
assert(pluginPageSource.includes("viewMode === 'graph' ? ("), 'Plugin content must render a relationship view')
assert(pluginPageSource.includes('selectedSuggestedTemplateId'), 'Suggested items must expose inspectable details')
assert(pluginPageSource.includes('heading="Suggested item"'), 'Suggested relationship views must identify their own records')
assert(pluginPageSource.includes("type PluginCollectionTab = 'active' | 'archived' | 'suggested'"), 'Suggested entries must live in a separate collection tab')
assert(pluginPageSource.includes('Suggested ({recommendedTemplates.length})'), 'The Suggested tab must show its available entry count')
assert(pluginPageSource.includes("collectionTab === 'suggested' && ("), 'Suggested search and filter controls must render only inside the Suggested tab')
assert(pluginPageSource.includes('value={suggestionSort}'), 'Suggested entries must expose independent sorting')
assert(pluginPageSource.includes('suggestionTags'), 'Suggested entries must expose independent tag filters')
assert(pluginPageSource.includes("setCollectionTab('active')"), 'Using a suggestion must return users to their active workspace entries')
assert(pluginPageSource.includes('const hasLoadedRef = useRef(false)'), 'Revisited plugin pages must retain rendered data during background refreshes')
assert(pluginPageSource.includes('const [contextRes, itemsRes, templatesRes] = await Promise.all(['), 'Plugin context, items, and suggestions must load in parallel')
assert(pluginPageSource.includes("forceTemplateRefresh ? '?refresh=1' : ''"), 'The explicit Refresh action must bypass the suggestion cache')
assert(pluginPageSource.includes('Actions <span className="text-xs">▾</span>'), 'Plugin refresh belongs in the standard Actions menu')
assert(appSource.includes('PLUGIN_NAV_ORDER_STORAGE_KEY'), 'Plugin navigation order must persist in the current browser')
assert(appSource.includes('handlePluginDragOver'), 'Plugin navigation items must support reordering')
assert(appSource.includes('PLUGIN_NAV_EXPANDED_STORAGE_KEY'), 'Plugin section expansion must persist in the current browser')
assert(appSource.includes('resolvePluginNavExpanded'), 'Plugin navigation must use the default-expanded persistence helper')
assert(appSource.includes('min-w-0 flex-1 overflow-auto overflow-x-hidden'), 'Plugin routes must not widen the mobile dashboard viewport')
assert(pluginPageSource.includes('max-w-2xl break-words text-sm leading-5'), 'Plugin descriptions must wrap into a readable multi-line measure')
assert(pluginPageSource.includes("localStorage.setItem(`clawmax-plugin-view-mode:${plugin.slug}`"), 'Plugin view selection must persist like core tabs')
assert(pluginPageSource.includes('history: []'), 'Suggested guardrails must normalize persistence-only history before preview')
assert(pluginPageSource.includes('runs: []'), 'Suggested evals must normalize persistence-only runs before preview')
assert(pluginPageSource.includes('fields: base.fields || {}'), 'Suggested generic plugins must normalize declarative fields before preview')
assert(pluginPageSource.includes('min-w-0 w-full sm:w-auto'), 'Plugin headers must stack without clipping on phone viewports')
assert(pluginPageSource.includes('grid w-full min-w-0 grid-cols-4 overflow-hidden rounded-lg border'), 'Plugin view controls must occupy four stable mobile columns')
assert(pluginPageSource.includes('type="range"'), 'Generic plugin forms must render declared slider controls')
assert(pluginPageSource.includes('grid-cols-[minmax(0,1fr)_7rem]'), 'Slider controls must reserve stable mobile space for exact values')
assert(pluginPageSource.includes('normalizePluginNumericValue(schema, event.target.value)'), 'Slider and numeric inputs must share bounded normalization')
assert(pluginPageSource.includes('function OptimizeRelationshipGraph'), 'Optimize must render a purpose-built relationship graph')
assert(pluginPageSource.includes('Optimization relationships'), 'Optimize graph must explain its plan relationships')
assert(pluginPageSource.includes('Dimensions connect to saved plans'), 'Active Optimize graph must distinguish dimensions, saved plans, and targets')
assert(pluginPageSource.includes('aria-label="Optimize relationship graph"'), 'Optimize graph must expose an accessible label')
assert(pluginPageSource.includes("item.id.startsWith('suggested:') ? 'Suggested plan'"), 'Optimize graph must distinguish suggested plans from Active plans')
assert(pluginPageSource.includes('height={canvasHeight}'), 'Optimize graphs must keep a stable visible height instead of scaling below the fold')
assert(pluginPageSource.includes('suggested plans preview their optimization dimensions'), 'Suggested Optimize graphs must explain placeholder targets')
assert(pluginPageSource.includes("title: 'Target and priority'"), 'Optimize editor must group target and priority controls')
assert(pluginPageSource.includes("title: 'Budgets'"), 'Optimize editor must group monthly and per-run budgets')
assert(pluginPageSource.includes("title: 'Quality and speed'"), 'Optimize editor must group semantic quality and duration gauges')
assert(pluginPageSource.includes('Tune with AI'), 'Optimize editor must expose an AI-assisted tuning panel')
assert(pluginPageSource.includes('applyOptimizeAssistantText'), 'Optimize AI assistance must apply structured changes to the current draft')
assert(pluginPageSource.includes('OPTIMIZE_AI_TUNING_EXPANDED_STORAGE_KEY'), 'Optimize AI tuning expansion must persist in the current browser')
assert(pluginPageSource.includes('lg:col-span-2'), 'Optimize AI tuning must occupy the full editor width above manual controls')
assert(pluginPageSource.includes('suggestionTemplates={filteredSuggestions}'), 'Suggested Optimize graphs must consume the visible suggestion templates directly')
assert(pluginPageSource.includes('No suggested plans match the current search and filters.'), 'Suggested Optimize graphs must explain a genuinely empty filtered result')
assert(pluginPageSource.includes('aria-pressed={selectedId === item.id}'), 'Optimize graph plans must expose their locked selected state')
assert(pluginPageSource.includes("isMuted ? 'opacity-10'"), 'Optimize graph edges unrelated to the selected plan must be muted')
assert(pluginPageSource.includes('selectedDimensions.has(label)'), 'Optimize graph selection must emphasize applicable attributes')
assert(pluginPageSource.includes('selectedTargetKeys.has(key)'), 'Optimize graph selection must emphasize the applicable destination')
assert(pluginPageSource.includes('const [hoveredId, setHoveredId]'), 'Optimize graphs must track a temporary hover preview')
assert(pluginPageSource.includes('const emphasizedId = hoveredId || selectedId'), 'Hover previews must temporarily override the locked graph selection')
assert(pluginPageSource.includes("onMouseEnter={() => setHoveredId(item.id)}"), 'Optimize plan nodes must preview their relationships on hover')
assert(!pluginPageSource.includes('useInlineGraphDetails'), 'Active and Archived Optimize graph selections must retain the standard detail drawer')
assert(pluginPageSource.includes('{selectedItem && ('), 'Selected Active and Archived records must open their detail drawer')
assert(pluginPageSource.includes('from-rose-400 via-amber-300 to-emerald-400'), 'Quality controls must expose a low-to-high semantic gauge')
assert(pluginPageSource.includes('from-emerald-400 via-amber-300 to-rose-400'), 'Duration controls must expose a fast-to-slow semantic gauge')
assert((agentsSource.match(/const menuWidth = 224/g) || []).length >= 3, 'Agent action menus must reserve enough width for icon and Template labels')
assert(pluginPageSource.includes("setError(`Could not use this suggestion:"), 'Suggestion failures must be visible instead of becoming rejected click promises')
assert(pluginPageSource.includes("{applying ? 'Adding...' : 'Use'}"), 'Suggestion actions must expose progress while applying')
assert(pluginPageSource.includes("applyingTemplateIds.has(template.id) ? 'Adding...' : 'Use'"), 'Suggestion list actions must expose progress while applying')
assert(manifests.every((manifest) => !/dormant|test plugin|mvp/i.test(`${manifest.name} ${manifest.description} ${manifest.version}`)), 'Enabled plugin UI copy must be product-ready')
assert(new Set(manifests.map((manifest) => manifest.icon)).size === manifests.length, 'Each first-party plugin must declare a distinct navigation icon')

console.log('PluginWorkspaceLayout.test.ts: 69 tests passed')
