import fs from 'fs'
import path from 'path'

const repoRoot = path.resolve(__dirname, '../../../..')
const pluginRoot = path.join(repoRoot, 'PLUGINS/test/plugin-lab-review-notes')
const manifest = JSON.parse(fs.readFileSync(path.join(pluginRoot, 'clawmax-plugin.json'), 'utf-8'))
const pageSource = fs.readFileSync(path.join(__dirname, 'pages/PluginWorkspacePage.tsx'), 'utf-8')
const checklistFiles = fs.readdirSync(path.join(pluginRoot, 'templates')).filter((file) => file.endsWith('.json')).sort()
const checklists = checklistFiles.map((file) => JSON.parse(fs.readFileSync(path.join(pluginRoot, 'templates', file), 'utf-8')))
const checklistByRelease = new Map(checklists.map((checklist) => [checklist.release, checklist]))
const stableChecklist = checklistByRelease.get('1.9.9 regression')
const previousChecklist = checklistByRelease.get('2.0.0 previous RCs')
const currentChecklist = checklistByRelease.get('2.0.0-test-rc16')
const allItems = checklists.flatMap((checklist) => checklist.items)

function assert(condition: boolean, message: string) {
  if (!condition) throw new Error(message)
}

assert(manifest.nav.label === 'Review', 'Review plugin must use a compact navigation label')
assert(manifest.nav.order === 1000, 'Review must be the last plugin in the default navigation order')
assert(manifest.ui.list.groupBy === 'release', 'Review records must be compartmentalized by release')
assert(manifest.ui.list.checkField === 'completed', 'Review records must declare their completion checkbox')
assert(manifest.recordSchema.properties.verifiedBy?.type === 'array', 'Review records must support aggregated prior tester confirmation')
assert(checklistFiles.length === 3, 'Review must expose exactly stable, cumulative, and current release sets')
assert(JSON.stringify(Array.from(checklistByRelease.keys()).sort()) === JSON.stringify(['1.9.9 regression', '2.0.0 previous RCs', '2.0.0-test-rc16']), 'Review set names must be stable and unambiguous')
assert(currentChecklist?.items.length === 5, 'Current RC16 must contain its five focused model-fit and release checks')
assert(previousChecklist?.items.length === 34, 'Unconfirmed earlier 2.0 checks must remain in the cumulative set')
assert(stableChecklist?.items.length === 14, 'The retained 1.9.9 regression set must contain fourteen end-to-end checks')
assert(new Set(allItems.map((item: any) => item.id)).size === allItems.length, 'Checklist item IDs must not duplicate across review sets')
assert(allItems.every((item: any) => /^Test:\s*.+\s+Pass:\s*.+$/i.test(item.description)), 'Every check must provide explicit Test and Pass instructions')
assert(currentChecklist?.items.every((item: any) => !/\b1\)/.test(item.description)), 'Current checks must use plain instructions instead of dense numbered procedures')
assert(currentChecklist?.items.every((item: any) => item.description.length <= 500), 'Current checks must stay concise enough for non-expert testers')
assert(allItems.every((item: any) => item.fields.notes === ''), 'New checklist notes must start empty and visually neutral')
assert(checklists.every((checklist) => checklist.defaults.fields.completed === false), 'Every review set must start unchecked')
assert(checklists.every((checklist) => checklist.defaults.fields.outcome === 'pending'), 'Every review set must start pending')
assert(checklists.every((checklist) => Array.isArray(checklist.defaults.fields.verifiedBy)), 'Every review set must initialize prior verification metadata')
assert(currentChecklist?.items.some((item: any) => item.id === 'rc16-agent-create-model-suggestion'), 'Current RC must verify creation-time model suggestions')
assert(currentChecklist?.items.some((item: any) => item.id === 'rc16-model-priority'), 'Current RC must verify model priority controls')
assert(currentChecklist?.items.some((item: any) => item.id === 'rc16-existing-agent-model-suggestion'), 'Current RC must verify existing-agent suggestions')
assert(currentChecklist?.items.some((item: any) => item.id === 'rc16-model-change-confirmation'), 'Current RC must verify explicit model change confirmation')
assert(currentChecklist?.items.some((item: any) => item.id === 'rc16-release-mobile-smoke'), 'Current RC must verify release startup and mobile layout')
assert(previousChecklist?.items.some((item: any) => item.id === 'rc15-builder-scoring'), 'Cumulative checks must retain RC15 Builder scoring')
assert(previousChecklist?.items.some((item: any) => item.id === 'rc15-agent-scoring'), 'Cumulative checks must retain RC15 agent scoring')
assert(previousChecklist?.items.some((item: any) => item.id === 'rc15-plugin-scoring'), 'Cumulative checks must retain RC15 plugin scoring')
assert(previousChecklist?.items.some((item: any) => item.id === 'rc15-security-export-regression'), 'Cumulative checks must retain RC15 security coverage')
assert(previousChecklist?.items.some((item: any) => item.id === 'rc14-sidebar-order'), 'Cumulative checks must retain restored sidebar order coverage')
assert(previousChecklist?.items.some((item: any) => item.id === 'rc14-plugin-collapse-persistence'), 'Cumulative checks must retain plugin collapse persistence')
assert(previousChecklist?.items.some((item: any) => item.id === 'rc13-mail-partner-visibility'), 'Cumulative checks must retain upgraded partner visibility')
assert(previousChecklist?.items.some((item: any) => item.id === 'rc13-gmail-oauth'), 'Cumulative checks must retain Gmail OAuth lifecycle')
assert(previousChecklist?.items.some((item: any) => item.id === 'rc13-microsoft-oauth'), 'Cumulative checks must retain Microsoft OAuth lifecycle')
assert(previousChecklist?.items.some((item: any) => item.id === 'plugin-layout-views'), 'Cumulative 2.0 checks must cover every plugin view')
assert(previousChecklist?.items.some((item: any) => item.id === 'guardrail-create-target'), 'Cumulative 2.0 checks must cover guardrail targeting')
assert(previousChecklist?.items.some((item: any) => item.id === 'eval-create-run'), 'Cumulative 2.0 checks must cover eval runs')
assert(previousChecklist?.items.some((item: any) => item.id === 'optimize-skeleton'), 'Cumulative 2.0 checks must cover public Optimize')
assert(
  previousChecklist?.items.find((item: any) => item.id === 'plugin-sidebar-mobile')?.fields.verifiedBy?.some((entry: string) => entry.includes('Max') && entry.includes('local Dev')),
  'Imported RC4/RC5 navigation verification must retain reviewer and environment provenance',
)
assert(
  !currentChecklist?.items.some((item: any) => (item.fields.verifiedBy || []).length > 0),
  'Earlier RC results must not pre-verify focused RC16 checks',
)
assert(stableChecklist?.items.some((item: any) => item.id === 'secret-runtime-redaction'), 'Stable regression checks must retain secret redaction coverage')
assert(stableChecklist?.items.some((item: any) => item.id === 'openrouter-provider'), 'Stable regression checks must retain OpenRouter coverage')
assert(stableChecklist?.items.some((item: any) => item.id === 'xai-provider'), 'Stable regression checks must retain xAI coverage')
assert(pageSource.includes('const isChecklist = Boolean(groupField && checkField)'), 'Checklist presentation must be manifest-driven')
assert(pageSource.includes('Start {release} checklist'), 'Review page must initialize a release with one clear action')
assert(pageSource.includes('function ChecklistItemRow'), 'Review page must render checklist rows instead of template cards')
assert(pageSource.includes("{notes ? 'Edit notes' : 'Add notes'}"), 'Checklist rows must expose note editing directly')
assert(pageSource.includes('aria-label="Release checklists"'), 'Review page must expose release tabs accessibly')
assert(pageSource.includes('const toggleCheck = async'), 'Review page must persist direct checkbox changes')
assert(pageSource.includes('isChecklist ? ('), 'Checklist suggestions must not use the generic card catalog')
assert(pageSource.includes('const setChecklistOutcome = async'), 'Review page must persist explicit pass and fail outcomes')
assert(pageSource.includes('aria-label={`Mark ${item.name} failed`}'), 'Checklist rows must expose a direct accessible fail action')
assert(pageSource.includes("outcome === 'failed'"), 'Failed checks must have a distinct visual state')
assert(pageSource.includes("completed ? 'line-through"), 'Completed checks must be crossed out')
assert(pageSource.includes(": notes\n          ? 'bg-yellow"), 'Commented pending checks must be highlighted')
assert(pageSource.includes('w-full min-w-0 max-w-7xl overflow-x-hidden'), 'Plugin pages must constrain narrow-screen horizontal overflow')
assert(pageSource.includes('w-full min-w-0 max-w-full overflow-hidden rounded-lg border border-sky-200'), 'Suggested cards must shrink within phone viewports')
assert(pageSource.includes('grid w-full min-w-0 grid-cols-4'), 'Plugin view controls must use four equal phone-width tracks')
assert(pageSource.includes('grid w-full min-w-0 grid-cols-3'), 'Plugin collection tabs must use three equal phone-width tracks')
assert(pageSource.includes('Export release review'), 'Review actions must expose a release report export')
assert(pageSource.includes('Archive release checklist'), 'Review actions must expose release-level archiving')
assert(pageSource.includes('Restore release checklist'), 'Review actions must expose release-level restoration')
assert(pageSource.includes('getCompletedReviewReleaseIdsToArchive'), 'Starting a new checklist must retire fully completed older releases')
assert(pageSource.includes('collectRecentRuntimeErrors'), 'Review exports must collect recent runtime errors')
assert(pageSource.includes('Reviewer name'), 'Review export must identify the reviewer')
assert(pageSource.includes('resolveReviewIdentity(user'), 'Review export must prefill identity from the authenticated user or browser fallback')
assert(pageSource.includes("kind === 'onprem' ? 'On-prem'"), 'Review export must identify local, cloud, and on-prem environments')
assert(pageSource.includes("item.description.match(/^Test:"), 'Review rows must separate actions from expected pass results')
assert(pageSource.includes('[overflow-wrap:anywhere]'), 'Review instructions and notes must wrap long evidence safely on narrow screens')
assert(pageSource.includes('Previously verified by {verifiedBy.join'), 'Review rows must identify aggregated prior confirmations')
assert(pageSource.includes("return ['1.9.9', '2.0.0', '2.0.0-test-rc16'].filter"), 'Review filters must stay limited to the three release families')

console.log('PluginReviewChecklist.test.ts: 69 tests passed')
